name: notheus
services:
  server:
    image: "waxer/projects:8.1"
    ports:
      - "${LISTENING_IP}:23004:80"
    volumes:
      - "${SITE_PATH}:/srv/http/"
  mysql:
    image: "mysql"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - server
    ports:
      - "${LISTENING_IP}:23005:3306"
    volumes:
      - "${MYSQL_DATA_PATH}:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "${LISTENING_IP}:8081:80"
    environment:
      - PMA_HOST=mysql
