parameters:
  api_constants.messages.success: "Ok" 
  api_constants.messages.error: "Your request failed"
  api_constants.id.notFound: 3
  api_constants.id.found: 2

services:
  _defaults:
    autowire: true     
    autoconfigure: true 

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\EventListener\ExceptionListener:
    $errorMessage: '%api_constants.messages.error%'
    $environment: '%env(APP_ENV)%'
